# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pySICMGUImain.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PySICMGUIMainWindow(object):
    def setupUi(self, PySICMGUIMainWindow):
        PySICMGUIMainWindow.setObjectName(_fromUtf8("PySICMGUIMainWindow"))
        PySICMGUIMainWindow.resize(1098, 776)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/pySICM48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PySICMGUIMainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(PySICMGUIMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setEnabled(True)
        self.mdiArea.setViewMode(QtGui.QMdiArea.SubWindowView)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.verticalLayout_2.addWidget(self.mdiArea)
        PySICMGUIMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PySICMGUIMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew = QtGui.QMenu(self.menuFile)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuScanmodes = QtGui.QMenu(self.menubar)
        self.menuScanmodes.setObjectName(_fromUtf8("menuScanmodes"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        PySICMGUIMainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(PySICMGUIMainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        PySICMGUIMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(PySICMGUIMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PySICMGUIMainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(PySICMGUIMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Tango/16x16/actions/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAddressAndPort = QtGui.QAction(PySICMGUIMainWindow)
        self.actionAddressAndPort.setObjectName(_fromUtf8("actionAddressAndPort"))
        self.actionSave = QtGui.QAction(PySICMGUIMainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExport = QtGui.QAction(PySICMGUIMainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionClose = QtGui.QAction(PySICMGUIMainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionQuit = QtGui.QAction(PySICMGUIMainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionEmpty = QtGui.QAction(PySICMGUIMainWindow)
        self.actionEmpty.setObjectName(_fromUtf8("actionEmpty"))
        self.actionStartScan = QtGui.QAction(PySICMGUIMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Tango/24x24/actions/gtk-media-play-ltr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Tango/24x24/actions/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStartScan.setIcon(icon2)
        self.actionStartScan.setIconVisibleInMenu(False)
        self.actionStartScan.setObjectName(_fromUtf8("actionStartScan"))
        self.actionStop_Scan = QtGui.QAction(PySICMGUIMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Tango/24x24/actions/media-playback-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Tango/24x24/actions/player_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStop_Scan.setIcon(icon3)
        self.actionStop_Scan.setObjectName(_fromUtf8("actionStop_Scan"))
        self.actionShow_controller_window = QtGui.QAction(PySICMGUIMainWindow)
        self.actionShow_controller_window.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/icons/Tango/24x24/devices/gnome-fs-client.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_controller_window.setIcon(icon4)
        self.actionShow_controller_window.setObjectName(_fromUtf8("actionShow_controller_window"))
        self.actionConnect = QtGui.QAction(PySICMGUIMainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(PySICMGUIMainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionControllerSettings = QtGui.QAction(PySICMGUIMainWindow)
        self.actionControllerSettings.setObjectName(_fromUtf8("actionControllerSettings"))
        self.actionControllerConnect = QtGui.QAction(PySICMGUIMainWindow)
        self.actionControllerConnect.setObjectName(_fromUtf8("actionControllerConnect"))
        self.actionControllerDisconnect = QtGui.QAction(PySICMGUIMainWindow)
        self.actionControllerDisconnect.setObjectName(_fromUtf8("actionControllerDisconnect"))
        self.actionFakeMode = QtGui.QAction(PySICMGUIMainWindow)
        self.actionFakeMode.setCheckable(True)
        self.actionFakeMode.setObjectName(_fromUtf8("actionFakeMode"))
        self.actionSaveAsTemplate = QtGui.QAction(PySICMGUIMainWindow)
        self.actionSaveAsTemplate.setObjectName(_fromUtf8("actionSaveAsTemplate"))
        self.actionSaveAsDefaultTemplate = QtGui.QAction(PySICMGUIMainWindow)
        self.actionSaveAsDefaultTemplate.setObjectName(_fromUtf8("actionSaveAsDefaultTemplate"))
        self.actionImport = QtGui.QAction(PySICMGUIMainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveAsTemplate)
        self.menuFile.addAction(self.actionSaveAsDefaultTemplate)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionControllerConnect)
        self.menuSettings.addAction(self.actionControllerDisconnect)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionControllerSettings)
        self.menuSetting.addAction(self.actionFakeMode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuScanmodes.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionShow_controller_window)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStartScan)
        self.toolBar.addAction(self.actionStop_Scan)

        self.retranslateUi(PySICMGUIMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PySICMGUIMainWindow)

    def retranslateUi(self, PySICMGUIMainWindow):
        PySICMGUIMainWindow.setWindowTitle(_translate("PySICMGUIMainWindow", "pySICM - GUI", None))
        self.menuFile.setTitle(_translate("PySICMGUIMainWindow", "File", None))
        self.menuNew.setTitle(_translate("PySICMGUIMainWindow", "&New", None))
        self.menuSettings.setTitle(_translate("PySICMGUIMainWindow", "Controller", None))
        self.menuScanmodes.setTitle(_translate("PySICMGUIMainWindow", "Scanmodes", None))
        self.menuSetting.setTitle(_translate("PySICMGUIMainWindow", "Settings", None))
        self.menuTools.setTitle(_translate("PySICMGUIMainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("PySICMGUIMainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("PySICMGUIMainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("PySICMGUIMainWindow", "&Open", None))
        self.actionOpen.setShortcut(_translate("PySICMGUIMainWindow", "Ctrl+O", None))
        self.actionAddressAndPort.setText(_translate("PySICMGUIMainWindow", "Address and port", None))
        self.actionSave.setText(_translate("PySICMGUIMainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("PySICMGUIMainWindow", "Ctrl+S", None))
        self.actionExport.setText(_translate("PySICMGUIMainWindow", "&Export", None))
        self.actionExport.setShortcut(_translate("PySICMGUIMainWindow", "Ctrl+E", None))
        self.actionClose.setText(_translate("PySICMGUIMainWindow", "&Close", None))
        self.actionClose.setShortcut(_translate("PySICMGUIMainWindow", "Ctrl+W", None))
        self.actionQuit.setText(_translate("PySICMGUIMainWindow", "&Quit", None))
        self.actionQuit.setShortcut(_translate("PySICMGUIMainWindow", "Ctrl+Q", None))
        self.actionEmpty.setText(_translate("PySICMGUIMainWindow", "Empty", None))
        self.actionStartScan.setText(_translate("PySICMGUIMainWindow", "StartScan", None))
        self.actionStartScan.setShortcut(_translate("PySICMGUIMainWindow", "F7", None))
        self.actionStop_Scan.setText(_translate("PySICMGUIMainWindow", "Stop Scan", None))
        self.actionStop_Scan.setToolTip(_translate("PySICMGUIMainWindow", "Stop current measurement", None))
        self.actionStop_Scan.setShortcut(_translate("PySICMGUIMainWindow", "F8", None))
        self.actionShow_controller_window.setText(_translate("PySICMGUIMainWindow", "show controller window", None))
        self.actionConnect.setText(_translate("PySICMGUIMainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("PySICMGUIMainWindow", "Disconnect", None))
        self.actionControllerSettings.setText(_translate("PySICMGUIMainWindow", "Settings", None))
        self.actionControllerConnect.setText(_translate("PySICMGUIMainWindow", "Connect", None))
        self.actionControllerDisconnect.setText(_translate("PySICMGUIMainWindow", "Disconnect", None))
        self.actionFakeMode.setText(_translate("PySICMGUIMainWindow", "Fake mode (development)", None))
        self.actionSaveAsTemplate.setText(_translate("PySICMGUIMainWindow", "Save as template", None))
        self.actionSaveAsDefaultTemplate.setText(_translate("PySICMGUIMainWindow", "Save as default template", None))
        self.actionImport.setText(_translate("PySICMGUIMainWindow", "Import", None))
        self.actionImport.setShortcut(_translate("PySICMGUIMainWindow", "Ctrl+I", None))

import unixres_rc
